spring:
  application:
    name: filters-app

  datasource:
    url: jdbc:h2:mem:filtersdb
    driver-class-name: org.h2.Driver
    username: user
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console
