server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: 'Filters App'
  profiles:
    active: test
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Tallinn
  datasource:
    url: jdbc:h2:mem:${APP_DB:filtersdb}
    driver-class-name: org.h2.Driver
    username: ${APP_DB_USER:user}
    password: ${APP_DB_PASSWORD:12345}
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: db/migration
    encoding: UTF-8
    enabled: false # change that to true in case you want to run flyway locally, not in container

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /filters-app-swagger-ui.html
    doc-expansion: none
    syntax-highlight:
      theme: monokai

