services:

  filters-app-backend:
    hostname: filters-app-backend
    container_name: filters_app_backend
    build:
      context: ../FiltersApp
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8081
      APP_DB: filtersdb
      APP_DB_HOST: filtersapp-db
      APP_DB_PORT: 5432
      APP_DB_USER: filters_user
      APP_DB_PASSWORD: 123456
    ports:
      - '8081:8081'
    networks:
      - filtersapp-net
    depends_on:
      - filtersapp-db
      - flyway

  filtersapp-db:
    image: 'postgres:17'
    container_name: filtersapp_db
    environment:
      POSTGRES_DB: filtersdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-filtersapp-data:/var/lib/postgresql/data
    ports:
      - '5332:5432'
    networks:
      - filtersapp-net

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    volumes:
      - ../flyway/migration:/flyway/sql
    depends_on:
      - filtersapp-db
    environment:
      FLYWAY_URL: jdbc:postgresql://filtersapp-db:5432/filtersdb
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
    command: migrate
    networks:
      - filtersapp-net

volumes:
  postgres-filtersapp-data:

networks:
  filtersapp-net:
